# Generated by Django 4.2.16 on 2024-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=100, unique=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'TokenCountTable',
            },
        ),
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table='UserRegistrations',
        ),
    ]
