# Generated by Django 4.2.16 on 2024-10-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tokencountmodel_alter_userregistrationmodel_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenCountModel',
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
        ),
        migrations.AlterModelTable(
            name='userregistrationmodel',
            table='user_registrations',
        ),
    ]
